name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add clang make bash python2
        apk add libintl icu-dev wget
        wget https://dot.net/v1/dotnet-install.sh && chmod 755 dotnet-install.sh && ./dotnet-install.sh -c 3.0 --install-dir ~/cli

    - name: Compile Sample App
      run: |
        export PATH=~/cli:$PATH # .net cli
        make clean all oelf eboot pkg_build

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    - name: Compress bin folder
      run: |
        tar -zcvf bin.tar.gz bin
    
    - uses: actions/upload-artifact@v2
      with:
        name: bin-${{ steps.slug.outputs.sha8 }}
        path: bin.tar.gz
